:concurrency: 5
:queues:
  - default

:scheduler:
  :schedule:
    mark_abandoned_carts:
      cron: '* * * * *'  # A cada hora
      class: MarkCartAsAbandonedJob
      queue: default
      description: "Marca carrinhos como abandonados após 3 horas de inatividade"